packages:
  - "apps/*"
  - "packages/*"
  - "external/*/*"
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  canvas: false
  esbuild: true
  prisma: true
  spawn-sync: true
  tesseract.js: true
  unrs-resolver: true
